Dockerfiles attempting to get cms and web running at same time

diff --git a/Dockerfile.cms b/Dockerfile.cms
--- a/Dockerfile.cms
+++ b/Dockerfile.cms
@@ -1,16 +1,62 @@
 ARG PRODUCTION_PLATFORM
 FROM --platform=$PRODUCTION_PLATFORM node:21-alpine AS base
 
+ARG PKG_MGMR
+ENV PKG_MGMR=${PKG_MGMR}
+
 FROM base AS builder
 WORKDIR /app
 
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 COPY . ./
 
-RUN $PKG_MGMR install --production --frozen-lockfile
-RUN $PKG_MGMR generate
-RUN $PKG_MGMR ks:build
-RUN $PKG_MGMR next telemetry disable
+RUN \
+  if [ -f yarn.lock ]; then \ 
+    yarn install --production --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then \ 
+    npm ci --production --frozen-lockfile; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    corepack enable pnpm && pnpm i --production --frozen-lockfile; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
+  fi
+# RUN $PKG_MGMR install --production --frozen-lockfile
+
+RUN \
+  if [ -f yarn.lock ]; then \ 
+    yarn generate; \
+  elif [ -f package-lock.json ]; then \ 
+    npm generate; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    pnpm generate; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
+  fi
+# RUN $PKG_MGMR generate
+
+RUN \
+  if [ -f yarn.lock ]; then \ 
+    yarn ks:build; \
+  elif [ -f package-lock.json ]; then \ 
+    npm ks:build; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    pnpm ks:build; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
+  fi
+# RUN $PKG_MGMR ks:build
+
+RUN \
+  if [ -f yarn.lock ]; then \ 
+    yarn next telemetry disable; \
+  elif [ -f package-lock.json ]; then \ 
+    npm next telemetry disable; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    pnpm next telemetry disable; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
+  fi
+# RUN $PKG_MGMR next telemetry disable
 
 # Learn more here: https://nextjs.org/telemetry
 ENV NEXT_TELEMETRY_DISABLED 1
@@ -38,4 +84,4 @@ EXPOSE $CMS_PORT
 ENV NODE_ENV production
 ENV PORT $CMS_PORT
 
-CMD [$PKG_MGMR, "ks:start"]
+CMD ["pnpm", "ks:start"]
diff --git a/Dockerfile.web.standalone b/Dockerfile.web.standalone
--- a/Dockerfile.web.standalone
+++ b/Dockerfile.web.standalone
@@ -39,7 +39,17 @@ RUN \
     echo "Lockfile not found." && exit 1; \
   fi
 
-# RUN yarn add sharp
+RUN \
+  if [ -f yarn.lock ]; then \ 
+    yarn add sharp; \
+  elif [ -f package-lock.json ]; then\ 
+    npm install sharp; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+  pnpm add sharp; \
+  else \
+    echo "Lockfile not found." && exit 1; \
+  fi
+
 # Learn more here: https://nextjs.org/telemetry
 ENV NEXT_TELEMETRY_DISABLED 1
 
