dockerfile fixes

diff --git a/Dockerfile.web.standalone b/Dockerfile.web.standalone
--- a/Dockerfile.web.standalone
+++ b/Dockerfile.web.standalone
@@ -6,23 +6,37 @@ FROM base AS builder
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# COPY package.json yarn.lock package-lock.json pnpm-lock.yaml ./
+# COPY package.json ./
+# COPY yarn.lock ./
+# COPY package-lock.json ./
+COPY pnpm-lock.yaml ./
 COPY . ./
 
 ## TODO just use $PKG_MGMR instead of this crazy if logic. Once I test it of course
 
 RUN \
-  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then \ 
+    yarn install --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then \ 
+    npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
   fi
 
+# RUN corepack enable pnpm && pnpm i --frozen-lockfile;
+
 RUN \
-  if [ -f yarn.lock ]; then yarn next telemetry disable; \
-  elif [ -f package-lock.json ]; then npm next telemetry disable; \
-  elif [ -f pnpm-lock.yaml ]; pnpm next telemetry disable; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then \ 
+    yarn next telemetry disable; \
+  elif [ -f package-lock.json ]; then\ 
+    npm next telemetry disable; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+  pnpm next telemetry disable; \
+  else \
+    echo "Lockfile not found." && exit 1; \
   fi
 
 # RUN yarn add sharp
@@ -31,17 +45,25 @@ ENV NEXT_TELEMETRY_DISABLED 1
 
 
 RUN \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then \ 
+    yarn run build; \
+  elif [ -f package-lock.json ]; then \ 
+    npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then \ 
+    corepack enable pnpm && pnpm run build; \
+  else \ 
+    echo "Lockfile not found." && exit 1; \
   fi
   
 RUN \
-  if [ -f yarn.lock ]; then yarn next telemetry disable; \
-  elif [ -f package-lock.json ]; then npm next telemetry disable; \
-  elif [ -f pnpm-lock.yaml ]; pnpm next telemetry disable; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then  \
+    yarn next telemetry disable; \
+  elif [ -f package-lock.json ]; then  \
+    npm next telemetry disable; \
+  elif [ -f pnpm-lock.yaml ];  then \
+    pnpm next telemetry disable; \
+  else \
+    echo "Lockfile not found." && exit 1; \
   fi
 
 # Production image, copy all the files and run next
